version: '3.8'

services:
  app:
    container_name: portfolio-client
    image: portfolio-client
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
